name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2.3.1
        - name: Install Dependencies
          run: |
            sudo apt-get update
            sudo apt-get install cmake doxygen ninja-build
            sudo apt-get install verilator
            sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra latexmk
        - name: Install Python
          run: |
            sudo apt-get install python3
            python3 -m pip install ivpm
        - name: Install Dependencies
          run: |
            python3 -m ivpm update --anonymous-git
        - name: Install and build
          run: |
            make html pdf
            touch build/html/.nojekyll

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@4.1.7
          with:
            branch: gh-pages # The branch the action should deploy to.
            folder: build/html # The folder the action should deploy.

