name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2.3.1
        - name: Configure Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'
        - name: Install Dependencies
          run: |
            sudo apt-get update
            sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra latexmk
        - name: Install Python Deps
          run: |
            python3 -m pip install ivpm
        - name: Install Dependencies
          run: |
            python3 -m ivpm update --anonymous-git
        - name: Install and build
          run: |
            make html pdf
            touch build/html/.nojekyll

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@4.1.7
          with:
            branch: gh-pages # The branch the action should deploy to.
            folder: build/html # The folder the action should deploy.

        - name: Build Wheel
          run: |
            python3 -m venv python
            ./python/bin/python3 -m pip install wheel twine 
            ./python/bin/python3 -m pip install setuptools --upgrade
            export BUILD_NUM=$GITHUB_RUN_ID
            ./python/bin/python3 setup.py bdist_wheel --universal
        - name: Publish to PyPi
          if: startsWith(github.ref, 'refs/heads/main')
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            user: __token__
            password: ${{ secrets.PYPI_API_TOKEN }}


